receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14278"

  otlp/loadbalancer:
    protocols:
      grpc:
        endpoint: localhost:4317
  otlp/backend-0:
    protocols:
      grpc:
        endpoint: localhost:55690
  otlp/backend-1:
    protocols:
      grpc:
        endpoint: localhost:55700
  otlp/backend-2:
    protocols:
      grpc:
        endpoint: localhost:55710
  otlp/backend-3:
    protocols:
      grpc:
        endpoint: localhost:55720

processors:
  tail_sampling/always_sample:
    decision_wait: 10s
    num_traces: 100
    expected_new_traces_per_sec: 10
    policies:
      [
        {
          name: always,
          type: always_sample
        }
      ]

  tail_sampling/850ms_latency:
    decision_wait: 10s
    num_traces: 100
    expected_new_traces_per_sec: 10
    policies:
      [
        {
          name: latency,
          type: latency,
          latency: { threshold_ms: 850 }
        }
      ]

  tail_sampling/900ms_latency:
    decision_wait: 10s
    num_traces: 100
    expected_new_traces_per_sec: 10
    policies:
      [
        {
          name: latency,
          type: latency,
          latency: { threshold_ms: 900 }
        }
      ]

exporters:
  logging:
  loadbalancing:
    protocol:
      otlp:
        timeout: 1s
        tls:
          insecure: true
    resolver:
      static:
        hostnames:
          - localhost:55690
          - localhost:55700
          - localhost:55710
          - localhost:55720
  jaeger:
    endpoint: jaeger_1:14250
    tls:
      insecure: true
  jaeger/2:
    endpoint: jaeger_2:14250
    tls:
      insecure: true
  jaeger/3:
    endpoint: jaeger_3:14250
    tls:
      insecure: true

service:
  pipelines:
    traces/loadbalancer:
      receivers:
        - jaeger
      processors: []
      exporters:
        - loadbalancing

    traces/backend-0:
      receivers:
        - otlp/backend-0
      processors: []
      exporters:
        - logging

    traces/backend-1:
      receivers:
        - otlp/backend-1
      processors: [tail_sampling/always_sample]
      exporters:
        - jaeger

    traces/backend-2:
      receivers:
        - otlp/backend-2
      processors: [tail_sampling/850ms_latency]
      exporters:
        - jaeger/2

    traces/backend-3:
      receivers:
        - otlp/backend-3
      processors: [tail_sampling/900ms_latency]
      exporters:
        - jaeger/3


